library:
	rapydscript compile -b lib/jappy.pyj > lib/baselib.js
tags:
	cat code_editor.tag.html | riot --stdin --config js/riot.config.js --stdout > js/codeeditor.js
	cat toolbar.tag.html | riot --stdin --config js/riot.config.js --stdout > js/toolbar.js
